### ISSUE TITLE
rpc: re-export jsonrpsee HttpClient and WsClient

### ISSUE THREAD

**Issue by SuperFluffy** [eigerco/celestia-node-rs#100]
`celestia-rpc` provides convenience functions to return a `HttpClient` and `WsClient`, but no way to actually name them other than importing `jsonrpsee` directly.

celestia-rpc should reexport these (and potentially all of `jsonrpsee_http_client`, `jsonrpsee_ws_client` and maybe others, haven't checked) so that downstream users need not directly depend on celestia-rpc's version of jsonrpsee.

**Comment by zvolin** [comment]
we could also just reexport the `jsonrpsee` itself

**Comment by SuperFluffy** [comment]
Heh, yeah, that's what I ended up doing in my extension trait lib. 🙂

**Comment by zvolin** [comment]
We've been discussing the re-export of jsonrpsee and we think we'd like to avoid it for now. I tried to found examples how is it usually done for crates exposing traits for jsonrpsee but unfortunately I couldn't find a lot of examples (looking at dependant crates on crates.io).
So instead we've thought about wrapping the jsonrpsee clients, so that user don't need to depend on it directly to properly type them, but if some more advanced client or client configuration is needed, then it'll require setting it up on user's end with jsonrpsee directly.
wdyt @SuperFluffy ?
