### ISSUE TITLE
Figure out multi-wasm-crate logging

### ISSUE THREAD

**Issue by fl0rek** [eigerco/celestia-node-rs#121]
Currently, our logging-setup function is set to run unconditionally as it's marked with `wasm_bindgen(start)`.
Make sure this doesn't works correctly when multiple wasm crates are used simultanously.

**Comment by zvolin** [comment]
It turns out that each wasm package has it's own environment. I created an app which has 2 wasm libraries and both have this setup function ran on wasm init:

```rs
#[wasm_bindgen(start)]
pub fn setup_logging() {
    console_error_panic_hook::set_once();
    tracing_wasm::set_as_global_default();
}
```

I later use them in js like so:

```
import init1, { Foo } from "/lib1/lib1.js";
import init2, { Bar } from "/lib2/lib2.js";

await init1();
await init2();
```

This causes both modules to have logging and panic hooks set and working. If I comment out the body of this setup function in one of them, then having it in the other one will not make the former logging or properly creating stack traces on panic, so it's unaffected.

Here's the [example](https://github.com/zvolin/two-wasm-modules-test).

I think we're fine with our setup function then. Without it, there would be no way for a user to set it up externally for us without wrapping our lib within his own wasm package.
