### ISSUE TITLE
stretch goals: Implement Peer Tracker

### ISSUE THREAD

**Issue by zvolin** [eigerco/celestia-node-rs#61]

**Comment by oblique** [comment]
When this is implemented, unit tests for client will start failing because response must be a valid one.

We can have this public API:

* `ExtendedHeader::genesis` contructor which creates a valid header of height 1.
* `ExtendedHeader::next_without_txs` method which creates a valid header of the `self.height()` + 1.

The above functions must be able to pass `ExtendedHeader::validate` and `ExtendedHeader::verify`.

**Comment by oblique** [comment]
This is done while implementing other tasks, except the part of peer scoring.
