### ISSUE TITLE
stretch goals: Introduce Session-based Request Distribution

### ISSUE THREAD

**Issue by zvolin** [eigerco/celestia-node-rs#62]

**Comment by oblique** [comment]
https://github.com/eigerco/celestia-node-rs/pull/67#discussion_r1327926574

**Comment by oblique** [comment]
Since partial responses are allowed:
* [Here](https://github.com/eigerco/celestia-node-rs/blob/9f0bdc8990222fdbd8f2822131e0fa54ed0d3ba1/node/src/exchange.rs#L336-L356) we should return the error *only* if vector is empty.
* [Here](https://github.com/eigerco/celestia-node-rs/blob/8df7715b7c79452610d5e3a85ba1b12bac1828b5/node/src/exchange/client.rs#L248-L254) in case of failure if some headers passed verification, we should return them instead of an error.

Session should retry requesting the remaining range.

**Comment by oblique** [comment]
We need to figure out this: Should requests that failed because of a connection error be retried?
